<?php

namespace App\Reporting;

use App\Audit\Auditor;
use App\Branding\Branding;
use App\Support\SpreadsheetCells;
use Spatie\SimpleExcel\SimpleExcelWriter;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Renders a built report as a self-contained HTML page or an XLSX workbook
 * (one sheet per table) and writes the export to the audit log.
 */
class ReportWriter
{
    public function __construct(
        private readonly Branding $branding,
        private readonly Auditor $auditor,
    ) {}

    public function download(UserReportResult $report, ReportFormat $format): StreamedResponse
    {
        $fileName = 'hdid-kimutatas-'.$report->from->format('Ymd').'-'.$report->until->format('Ymd').'.'.$format->value;

        $this->auditor->record('report.exported', null, [
            'format' => $format->value,
            'from' => $report->from->toDateString(),
            'until' => $report->until->toDateString(),
            'sections' => $report->sectionValues(),
            'rows' => $report->rowCount(),
        ], $report->generatedBy);

        return response()->streamDownload(function () use ($report, $format): void {
            echo match ($format) {
                ReportFormat::Html => $this->html($report),
                ReportFormat::Xlsx => $this->xlsx($report),
            };
        }, $fileName, ['Content-Type' => $format->contentType()]);
    }

    public function html(UserReportResult $report): string
    {
        return view('reports.user-report', [
            'report' => $report,
            'appName' => $this->branding->appName(),
            'palette' => $this->branding->palette(),
        ])->render();
    }

    /**
     * The workbook bytes. Written to a temporary file first because the
     * XLSX writer needs a seekable target.
     */
    public function xlsx(UserReportResult $report): string
    {
        $path = tempnam(sys_get_temp_dir(), 'hdid-report').'.xlsx';

        try {
            $writer = SimpleExcelWriter::create($path)->noHeaderRow();
            $writer->nameCurrentSheet($this->sheetName(__('Summary')));
            $writer->addRows(array_map(SpreadsheetCells::xlsxRow(...), [
                [__('Report'), $this->branding->appName()],
                [__('Period'), $report->from->toDateString().' – '.$report->until->toDateString()],
                [__('Generated at'), $report->generatedAt->toDateTimeString()],
                [__('Generated by'), $report->generatedBy->name],
            ]));

            $used = [];
            foreach ($report->tables as $index => $table) {
                $writer->addNewSheetAndMakeItCurrent($this->sheetName($table->title, $index + 1, $used));
                $writer->addRow(SpreadsheetCells::xlsxRow($table->headers));
                foreach ($table->rows as $row) {
                    $writer->addRow(SpreadsheetCells::xlsxRow($row));
                }
                if ($table->totals !== null) {
                    $writer->addRow(SpreadsheetCells::xlsxRow($table->totals));
                }
            }
            $writer->close();

            return (string) file_get_contents($path);
        } finally {
            @unlink($path);
        }
    }

    /**
     * Excel limits sheet names to 31 characters without []:*?/\ and wants
     * them unique within the workbook.
     *
     * @param  array<string, true>  $used
     */
    private function sheetName(string $title, int $index = 0, array &$used = []): string
    {
        $name = trim(mb_substr(preg_replace('/[\[\]:*?\/\\\\]/', ' ', $title) ?? $title, 0, 31));
        if ($name === '' || isset($used[$name])) {
            $name = trim(mb_substr($name, 0, 28)).' '.$index;
        }
        $used[$name] = true;

        return $name;
    }
}
