<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $appName }} – {{ __('Staff report') }} {{ $report->from->format(\App\Support\HuDate::DATE) }} – {{ $report->until->format(\App\Support\HuDate::DATE) }}</title>
    {{-- Inline values from the configured palette: the file is opened offline, outside the app. --}}
    <style>
        body { margin: 0; padding: 24px; background: {{ $palette['background'] }}; color: {{ $palette['text'] }}; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; font-size: 13px; }
        .sheet { max-width: 1400px; margin: 0 auto; background: {{ $palette['surface'] }}; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,.08); overflow: hidden; }
        .head { background: {{ $palette['primary'] }}; color: #fff; padding: 20px 32px; }
        .head h1 { margin: 0 0 4px; font-size: 20px; }
        .head p { margin: 0; opacity: .9; }
        .body { padding: 24px 32px; }
        h2 { font-size: 16px; margin: 28px 0 8px; }
        h2:first-child { margin-top: 0; }
        p.note { margin: 0 0 8px; color: {{ $palette['muted'] }}; }
        .scroll { overflow-x: auto; }
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid color-mix(in srgb, {{ $palette['muted'] }} 25%, {{ $palette['surface'] }}); padding: 5px 8px; text-align: left; white-space: nowrap; }
        th { background: color-mix(in srgb, {{ $palette['muted'] }} 10%, {{ $palette['surface'] }}); font-weight: 600; }
        td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
        tr.totals td { font-weight: 700; background: color-mix(in srgb, {{ $palette['muted'] }} 6%, {{ $palette['surface'] }}); }
        .empty { color: {{ $palette['muted'] }}; font-style: italic; }
        .foot { padding: 12px 32px; background: {{ $palette['background'] }}; color: {{ $palette['muted'] }}; font-size: 12px; }
        @media print { body { background: #fff; padding: 0; } .sheet { box-shadow: none; border-radius: 0; } .head { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
    </style>
</head>
<body>
<div class="sheet">
    <div class="head">
        <h1>{{ $appName }} – {{ __('Staff report') }}</h1>
        <p>{{ __('Period') }}: {{ $report->from->format(\App\Support\HuDate::DATE) }} – {{ $report->until->format(\App\Support\HuDate::DATE) }}</p>
    </div>
    <div class="body">
        @forelse ($report->tables as $table)
            <h2>{{ $table->title }}</h2>
            @if ($table->note)
                <p class="note">{{ $table->note }}</p>
            @endif
            @if ($table->rows === [])
                <p class="empty">{{ __('No data in this period.') }}</p>
            @else
                <div class="scroll">
                    <table>
                        <thead>
                            <tr>
                                @foreach ($table->headers as $i => $header)
                                    <th class="{{ $i > 0 && is_numeric($table->rows[0][$i] ?? null) ? 'num' : '' }}">{{ $header }}</th>
                                @endforeach
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($table->rows as $row)
                                <tr>
                                    @foreach ($row as $i => $cell)
                                        <td class="{{ $i > 0 && is_numeric($cell) ? 'num' : '' }}">{{ $cell ?? '' }}</td>
                                    @endforeach
                                </tr>
                            @endforeach
                            @if ($table->totals !== null)
                                <tr class="totals">
                                    @foreach ($table->totals as $i => $cell)
                                        <td class="{{ $i > 0 && is_numeric($cell) ? 'num' : '' }}">{{ $cell ?? '' }}</td>
                                    @endforeach
                                </tr>
                            @endif
                        </tbody>
                    </table>
                </div>
            @endif
        @empty
            <p class="empty">{{ __('No part was selected.') }}</p>
        @endforelse
    </div>
    <div class="foot">
        {{ __('Generated at') }}: {{ $report->generatedAt->format(\App\Support\HuDate::DATETIME) }} · {{ __('Generated by') }}: {{ $report->generatedBy->name }}
    </div>
</div>
</body>
</html>
