<?php

namespace App\Settings;

/**
 * Every runtime-configurable business decision. Values are stored in the
 * `settings` table; the defaults below apply until an admin changes them.
 */
enum SettingKey: string
{
    // Branding (shared by the admin panel and the client site)
    case BrandingAppName = 'branding.app_name';
    case BrandingLogo = 'branding.logo';
    case BrandingFavicon = 'branding.favicon';
    case BrandingBackgroundImage = 'branding.background_image';
    case BrandingLoginBackgroundImage = 'branding.login_background_image';
    case BrandingAdminLoginBackgroundImage = 'branding.admin_login_background_image';
    case BrandingPrimaryColor = 'branding.primary_color';
    case BrandingAccentColor = 'branding.accent_color';
    case BrandingBackgroundColor = 'branding.background_color';
    case BrandingSurfaceColor = 'branding.surface_color';
    case BrandingTextColor = 'branding.text_color';
    case BrandingMutedTextColor = 'branding.muted_text_color';

    // Premium look of the client portal
    case PremiumAccentColor = 'premium.accent_color';
    case PremiumBadgeLabel = 'premium.badge_label';
    case PremiumBackgroundImage = 'premium.background_image';
    case PremiumLoginBackgroundImage = 'premium.login_background_image';

    // Client list: hide the directory-only accounts (no portal access, open, no history) by default
    case ClientsListRelevantOnly = 'clients.list_relevant_only';

    // Menu badge with the number of explicit-premium clients still waiting for a sponsor link
    case ClientsUnlinkedBadge = 'clients.unlinked_badge';
    case ClientsDirectoryFields = 'clients.directory_fields';

    // Packages that grant portal access, by service level
    case PackagesPremium = 'packages.premium';
    case PackagesStandard = 'packages.standard';

    // Support contact shown to clients, by service level
    case SupportStandardEmail = 'support.standard_email';
    case SupportStandardPhone = 'support.standard_phone';
    case SupportStandardHours = 'support.standard_hours';
    case SupportPremiumEmail = 'support.premium_email';
    case SupportPremiumPhone = 'support.premium_phone';
    case SupportPremiumHours = 'support.premium_hours';

    // Client portal content
    case PortalFooterText = 'portal.footer_text';
    case PortalLegalName = 'portal.legal_name';
    case PortalPrivacyUrl = 'portal.privacy_url';
    case PortalTermsUrl = 'portal.terms_url';
    case PortalImprintUrl = 'portal.imprint_url';
    case PortalNewsOnOverview = 'portal.news_on_overview';
    case PortalMaxPhoneNumbersPerClient = 'portal.max_phone_numbers_per_client';
    case PortalPhoneVerificationEnabled = 'portal.phone_verification_enabled';

    // Client login methods
    case ClientLoginMagicLinkEnabled = 'client_login.magic_link.enabled';
    case ClientLoginMagicLinkTtlMinutes = 'client_login.magic_link.ttl_minutes';
    case ClientLoginOtpSmsEnabled = 'client_login.otp_sms.enabled';
    case ClientLoginOtpSmsTtlMinutes = 'client_login.otp_sms.ttl_minutes';
    case ClientLoginOtpSmsLength = 'client_login.otp_sms.length';
    case ClientLoginOtpMaxAttempts = 'client_login.otp_sms.max_attempts';

    // Staff login
    case UserLoginPasswordEnabled = 'user_login.password.enabled';

    // SSO providers (secrets and endpoints live in config/hdid.php)
    case UserSsoAdfsEnabled = 'sso.user.adfs.enabled';
    case UserSsoEntraEnabled = 'sso.user.entra.enabled';
    case ClientSsoAdfsEnabled = 'sso.client.adfs.enabled';
    case ClientSsoEntraEnabled = 'sso.client.entra.enabled';

    // Identification: question and answer sessions
    case QaMinAnsweredQuestionsRequired = 'identification.qa.min_answered_questions_required';
    case QaMaxQuestionsPerSession = 'identification.qa.max_questions_per_session';
    case QaMinAcceptedToPass = 'identification.qa.min_accepted_to_pass';
    case QaMaxRejectedToFail = 'identification.qa.max_rejected_to_fail';
    case QaSessionTtlMinutes = 'identification.qa.session_ttl_minutes';

    // Identification: PIN
    case PinMinLength = 'identification.pin.min_length';
    case PinMaxLength = 'identification.pin.max_length';
    case PinMaxFailedAttempts = 'identification.pin.max_failed_attempts';
    case PinLockoutMinutes = 'identification.pin.lockout_minutes';
    case PinAgentVerificationEnabled = 'identification.pin.agent_verification_enabled';
    case PinClientChangesEnabled = 'identification.pin.client_changes_enabled';
    case PinUniqueRequired = 'identification.pin.unique_required';

    // Identification: one-time code generated by the client (portal or mobile app), read to the IVR or the agent
    case MobileOtpLength = 'identification.mobile_otp.length';
    case MobileOtpTtlMinutes = 'identification.mobile_otp.ttl_minutes';
    case IvrCodeLength = 'identification.ivr_code.length';

    // Identification: how many code / PIN checks one agent may run per hour
    case AgentAttemptsPerHour = 'identification.agent_attempts_per_hour';

    // External sync
    case SyncMissedRunsBeforeClose = 'sync.missed_runs_before_close';
    case SyncUniqueDomains = 'sync.unique_domains';
    case SyncUserDomains = 'sync.user_email_domains';
    case SyncClientDomains = 'sync.client_email_domains';
    case SyncColumnMapping = 'sync.column_mapping';
    case SyncApiDataPath = 'sync.api.data_path';
    case SyncApiPageParam = 'sync.api.page_param';
    case SyncMinRowsRatioPercent = 'sync.min_rows_ratio_percent';
    case SyncExpectedIntervalHours = 'sync.expected_interval_hours';
    case SyncCsvEncoding = 'sync.csv_encoding';
    case SyncExportPayload = 'sync.export_payload';

    // Call center
    case CallsRetentionHours = 'calls.retention_hours';
    case CallsDashboardPollSeconds = 'calls.dashboard_poll_seconds';
    case CallsQueueTiers = 'calls.queue_tiers';
    case CallsDefaultTier = 'calls.default_tier';

    // Data retention (years); the prune task runs daily
    case RetentionGeneralYears = 'retention.general_years';
    case RetentionShortLivedYears = 'retention.short_lived_years';
    case CallsStaleAfterHours = 'calls.stale_after_hours';

    public function type(): SettingType
    {
        return match ($this) {
            self::ClientLoginMagicLinkEnabled,
            self::ClientLoginOtpSmsEnabled,
            self::UserLoginPasswordEnabled,
            self::PortalNewsOnOverview,
            self::PortalPhoneVerificationEnabled,
            self::UserSsoAdfsEnabled,
            self::UserSsoEntraEnabled,
            self::ClientSsoAdfsEnabled,
            self::ClientSsoEntraEnabled,
            self::PinAgentVerificationEnabled,
            self::PinClientChangesEnabled,
            self::PinUniqueRequired,
            self::ClientsListRelevantOnly,
            self::SyncUniqueDomains,
            self::ClientsUnlinkedBadge => SettingType::Boolean,

            self::ClientLoginMagicLinkTtlMinutes,
            self::ClientLoginOtpSmsTtlMinutes,
            self::ClientLoginOtpSmsLength,
            self::ClientLoginOtpMaxAttempts,
            self::QaMinAnsweredQuestionsRequired,
            self::QaMaxQuestionsPerSession,
            self::QaMinAcceptedToPass,
            self::QaMaxRejectedToFail,
            self::QaSessionTtlMinutes,
            self::PinMinLength,
            self::PinMaxLength,
            self::PinMaxFailedAttempts,
            self::PinLockoutMinutes,
            self::MobileOtpLength,
            self::IvrCodeLength,
            self::MobileOtpTtlMinutes,
            self::AgentAttemptsPerHour,
            self::SyncMissedRunsBeforeClose,
            self::SyncMinRowsRatioPercent,
            self::SyncExpectedIntervalHours,
            self::RetentionGeneralYears,
            self::RetentionShortLivedYears,
            self::CallsRetentionHours,
            self::CallsStaleAfterHours,
            self::PortalMaxPhoneNumbersPerClient,
            self::CallsDashboardPollSeconds => SettingType::Integer,

            self::BrandingPrimaryColor,
            self::BrandingAccentColor,
            self::BrandingBackgroundColor,
            self::BrandingSurfaceColor,
            self::BrandingTextColor,
            self::BrandingMutedTextColor,
            self::PremiumAccentColor => SettingType::Color,

            self::BrandingLogo,
            self::BrandingFavicon,
            self::BrandingBackgroundImage,
            self::BrandingLoginBackgroundImage,
            self::BrandingAdminLoginBackgroundImage,
            self::PremiumBackgroundImage,
            self::PremiumLoginBackgroundImage => SettingType::Image,

            self::PortalFooterText, self::SyncExportPayload => SettingType::LongText,

            self::SyncUserDomains,
            self::SyncClientDomains,
            self::PackagesPremium,
            self::PackagesStandard,
            self::CallsQueueTiers,
            self::ClientsDirectoryFields,
            self::SyncColumnMapping => SettingType::Json,

            default => SettingType::Text,
        };
    }

    public function default(): mixed
    {
        return match ($this) {
            self::BrandingAppName => 'Helpdesk ID',
            self::BrandingLogo, self::BrandingFavicon => null,
            self::BrandingBackgroundImage, self::BrandingLoginBackgroundImage, self::BrandingAdminLoginBackgroundImage => null,
            self::BrandingPrimaryColor => '#36495D',
            self::BrandingAccentColor => '#4F6478',
            self::BrandingBackgroundColor => '#F4F5F6',
            self::BrandingSurfaceColor => '#FFFFFF',
            self::BrandingTextColor => '#1E252D',
            self::BrandingMutedTextColor => '#5E6975',

            self::PremiumAccentColor => '#C9A227',
            self::PremiumBadgeLabel => null,
            self::PremiumBackgroundImage, self::PremiumLoginBackgroundImage => null,

            self::PackagesPremium, self::PackagesStandard => [],

            self::SupportStandardEmail, self::SupportStandardPhone, self::SupportStandardHours => null,
            self::SupportPremiumEmail, self::SupportPremiumPhone, self::SupportPremiumHours => null,

            self::PortalFooterText => null,
            self::PortalLegalName => null,
            self::PortalPrivacyUrl, self::PortalTermsUrl, self::PortalImprintUrl => null,
            self::PortalNewsOnOverview => true,
            self::PortalMaxPhoneNumbersPerClient => 5,
            self::PortalPhoneVerificationEnabled => false,

            self::ClientLoginMagicLinkEnabled => true,
            self::ClientLoginMagicLinkTtlMinutes => 4320,
            self::ClientLoginOtpSmsEnabled => false,
            self::ClientLoginOtpSmsTtlMinutes => 5,
            self::ClientLoginOtpSmsLength => 6,
            self::ClientLoginOtpMaxAttempts => 5,

            self::UserLoginPasswordEnabled => true,

            self::UserSsoAdfsEnabled,
            self::UserSsoEntraEnabled,
            self::ClientSsoAdfsEnabled,
            self::ClientSsoEntraEnabled => false,

            self::QaMinAnsweredQuestionsRequired => 5,
            self::QaMaxQuestionsPerSession => 4,
            self::QaMinAcceptedToPass => 2,
            self::QaMaxRejectedToFail => 2,
            self::QaSessionTtlMinutes => 30,

            self::PinMinLength => 6,
            self::PinMaxLength => 10,
            self::PinMaxFailedAttempts => 5,
            self::PinLockoutMinutes => 30,
            self::PinAgentVerificationEnabled => false,
            self::PinClientChangesEnabled => false,
            self::PinUniqueRequired => true,

            self::ClientsListRelevantOnly => true,
            self::ClientsUnlinkedBadge => true,
            self::ClientsDirectoryFields => [],

            self::MobileOtpLength, self::IvrCodeLength => 8,
            self::MobileOtpTtlMinutes => 5,
            self::AgentAttemptsPerHour => 50,

            self::SyncMissedRunsBeforeClose => 2,
            self::SyncMinRowsRatioPercent => 50,
            self::SyncExpectedIntervalHours => 24,
            self::SyncCsvEncoding => 'UTF-8',
            self::SyncExportPayload => null,
            self::SyncUserDomains => [],
            self::SyncClientDomains => [],
            self::SyncUniqueDomains => true,
            self::SyncApiDataPath => 'data',
            self::SyncApiPageParam => null,
            self::SyncColumnMapping => [
                'external_id' => 'external_user_id',
                'name' => 'name',
                'email' => 'email',
                'company' => 'company',
                'title' => 'title',
                'department' => 'department',
                'login_name' => 'login_name',
                'room' => 'room',
                'employment_status' => 'employment_status',
                'phones' => 'phone',
                'implicit_package' => 'implicit_package',
                'explicit_package' => 'explicit_package',
            ],

            self::CallsRetentionHours => 24,
            self::CallsDashboardPollSeconds => 5,
            self::CallsQueueTiers => [],
            self::CallsDefaultTier => 'premium',

            self::RetentionGeneralYears => 5,
            self::RetentionShortLivedYears => 2,
            self::CallsStaleAfterHours => 6,
        };
    }

    public function group(): string
    {
        return explode('.', $this->value, 2)[0];
    }

    public function label(): string
    {
        return __(ucfirst(str_replace(['_', '.'], ' ', explode('.', $this->value, 2)[1])));
    }

    public function groupLabel(): string
    {
        return __(ucfirst(str_replace('_', ' ', $this->group())));
    }
}
